# Generated by Django 2.1.1 on 2018-09-26 00:48

from django.db import migrations

def cargar_proyectos_predeterminados(apps, schema_editor):
    Proyecto = apps.get_model('projects', 'Proyecto')
    # titulo, descripcion, url, fecha_creacion, imagen, fecha_modificacion
    proyectos = range(1,11) # [1,2,3,4,5,6,7,8,9,10]
    for item in proyectos:
        Proyecto.objects.create(
            titulo='Titulo proyecto' + str(item),
            descripcion="Descripcion demo" + str(item),
            url= f"http://mysitio.{item}.com"
        )

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180926_0006'),
    ]

    operations = [
        migrations.RunPython(cargar_proyectos_predeterminados),
    ]
