# Generated by Django 2.1.1 on 2018-09-26 01:51

from django.db import migrations
from django.utils.text import slugify

def crear_post(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    User = apps.get_model('auth', 'User')
    usuario = User.objects.first() # Obtengo el primer registro de User
    posts = range(1, 11)


    for item in posts:
        title = 'Titulo Post '+str(item)
        slug = slugify(title)
        Post.objects.create(
            titulo=title,
            author=usuario,
            slug=slug
        )

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_post),
    ]
